### ISSUE TITLE
Update to MoreUnit 3.3.0 fails in eclipse 2021-06

### ISSUE THREAD

**Issue by dpolivaev** [MoreUnit/MoreUnit-Eclipse#120] opened 2021-09-06 08:22 UTC
Cannot complete the install because one or more required items could not be found.
  Software being installed: MoreUnit For Java: Mock Support 3.3.0 (org.moreunit.mock.feature.group 3.3.0)
  Missing requirement: MoreUnit Mocking Support 3.3.0 (org.moreunit.mock 3.3.0) requires 'osgi.bundle; org.jboss.tools.common.jaxb 3.6.100' but it could not be found
  Cannot satisfy dependency:
    From: MoreUnit For Java: Mock Support 3.3.0 (org.moreunit.mock.feature.group 3.3.0)
    To: org.eclipse.equinox.p2.iu; org.moreunit.mock [3.3.0,3.3.0]

**Comment by apupier** [comment] 2021-09-06 08:24
Thanks for reporting the issue.

This is a duplicate of #118

**Closed by apupier** 2021-09-06 08:24 UTC
